title: Default Page

tabs:
  content:
    label: Inhoud
    columns:
      main:
        width: 2/3
        sections:
          fields:
            type: fields
            fields:
              title:
                type: text
                label: Paginatitel
              body:
                type: writer
                label: Tekst
                marks:
                  - bold
                  - italic
                  - link
      sidebar:
        width: 1/3
        sections:
          pages:
            type: pages
            template: default
          files:
            type: files

